name: Deploy to Production

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production # Add environment protection

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project for production
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY }}
          VITE_STRIPE_PUBLIC_KEY: ${{ secrets.PROD_STRIPE_PUBLIC_KEY }}
          NODE_ENV: production

      - name: Deploy to Production Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.PROD_FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          protocol: ftps
          server-dir: ./
          local-dir: ./dist/
          security: loose
          dangerous-clean-slate: true

      - name: Notify deployment success
        if: success()
        run: |
          echo "Production deployment completed successfully!"
          echo "Deployed to: ${{ secrets.PROD_FTP_SERVER }}"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "Production deployment failed!"
          echo "Check the logs for more details." 